# Generated by Django 3.2.10 on 2022-06-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appwards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='design',
            field=models.IntegerField(default=1),
        ),
    ]
