# Generated by Django 3.2.10 on 2022-06-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appwards', '0002_auto_20220613_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='information',
            new_name='info',
        ),
    ]
